### ISSUE TITLE
RangeError (index): Index out of range: index should be less than ****: ****

### ISSUE THREAD

**Issue by xayoung** [best-flutter/gbk2utf8#1]
error log:
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
RangeError (index): Index out of range: index should be less than 12338: 12338
#0      Uint8List.[] (dart:typed_data/runtime/libtyped_data_patch.dart:2830:7)
#1      gbk2unicode (package:gbk2utf8/src/convert.dart:28:22)
#2      gbk2utf8 (package:gbk2utf8/src/convert.dart:6:23)
#3      decodeGbk (package:gbk2utf8/src/convert.dart:10:45)

**Comment by jzoom** [comment]
Could you paste the text you want to convert? 能贴下原始文本吗

**Comment by xayoung** [comment]
原始文本
[json-error.txt](https://github.com/best-flutter/gbk2utf8/files/2374076/json-error.txt)
